"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientMessage = exports.ClientMessage_Which = exports.Config = exports.MdMessage = exports.MdMessage_Which = exports.Heartbeat = exports.Kline = exports.KlineInterval = exports.Summary = exports.Trades = exports.Trades_Trade = exports.MarketByOrderDiff = exports.MarketByOrderDiff_Diff = exports.OrderOp = exports.MarketByOrder = exports.MarketByOrder_Order = exports.MarketByPriceDiff = exports.MarketByPriceDiff_Diff = exports.DiffOp = exports.MarketByPrice = exports.MarketByPrice_Level = exports.Side = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = BigInt("0x9c4a7243ef808f4c");
var Side;
(function (Side) {
    Side[Side["BID"] = 0] = "BID";
    Side[Side["ASK"] = 1] = "ASK";
})(Side = exports.Side || (exports.Side = {}));
class MarketByPrice_Level extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(16, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    toString() { return "MarketByPrice_Level_" + super.toString(); }
}
exports.MarketByPrice_Level = MarketByPrice_Level;
MarketByPrice_Level._capnp = { displayName: "Level", id: "987a7e078dee1837", size: new capnp_ts_1.ObjectSize(24, 0) };
class MarketByPrice extends capnp_ts_1.Struct {
    adoptLevels(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownLevels() { return capnp_ts_1.Struct.disown(this.getLevels()); }
    getLevels() { return capnp_ts_1.Struct.getList(0, MarketByPrice._Levels, this); }
    hasLevels() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initLevels(length) { return capnp_ts_1.Struct.initList(0, MarketByPrice._Levels, length, this); }
    setLevels(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getChunk() { return capnp_ts_1.Struct.getUint32(0, this); }
    setChunk(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getNumChunks() { return capnp_ts_1.Struct.getUint32(4, this); }
    setNumChunks(value) { capnp_ts_1.Struct.setUint32(4, value, this); }
    toString() { return "MarketByPrice_" + super.toString(); }
}
exports.MarketByPrice = MarketByPrice;
MarketByPrice.Level = MarketByPrice_Level;
MarketByPrice._capnp = { displayName: "MarketByPrice", id: "f3322fc4d3725060", size: new capnp_ts_1.ObjectSize(8, 1) };
var DiffOp;
(function (DiffOp) {
    DiffOp[DiffOp["ADD"] = 0] = "ADD";
    DiffOp[DiffOp["REMOVE"] = 1] = "REMOVE";
    DiffOp[DiffOp["REPLACE"] = 2] = "REPLACE";
})(DiffOp = exports.DiffOp || (exports.DiffOp = {}));
class MarketByPriceDiff_Diff extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(16, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    getOp() { return capnp_ts_1.Struct.getUint16(18, this); }
    setOp(value) { capnp_ts_1.Struct.setUint16(18, value, this); }
    toString() { return "MarketByPriceDiff_Diff_" + super.toString(); }
}
exports.MarketByPriceDiff_Diff = MarketByPriceDiff_Diff;
MarketByPriceDiff_Diff._capnp = { displayName: "Diff", id: "f248c3f0ab609a5b", size: new capnp_ts_1.ObjectSize(24, 0) };
class MarketByPriceDiff extends capnp_ts_1.Struct {
    adoptDiffs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownDiffs() { return capnp_ts_1.Struct.disown(this.getDiffs()); }
    getDiffs() { return capnp_ts_1.Struct.getList(0, MarketByPriceDiff._Diffs, this); }
    hasDiffs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiffs(length) { return capnp_ts_1.Struct.initList(0, MarketByPriceDiff._Diffs, length, this); }
    setDiffs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByPriceDiff_" + super.toString(); }
}
exports.MarketByPriceDiff = MarketByPriceDiff;
MarketByPriceDiff.Diff = MarketByPriceDiff_Diff;
MarketByPriceDiff._capnp = { displayName: "MarketByPriceDiff", id: "d0332521c2c8b8c0", size: new capnp_ts_1.ObjectSize(0, 1) };
class MarketByOrder_Order extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getExchangeOrderId() { return capnp_ts_1.Struct.getUint64(16, this); }
    setExchangeOrderId(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(24, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(24, value, this); }
    toString() { return "MarketByOrder_Order_" + super.toString(); }
}
exports.MarketByOrder_Order = MarketByOrder_Order;
MarketByOrder_Order._capnp = { displayName: "Order", id: "f3945c08e6ddb772", size: new capnp_ts_1.ObjectSize(32, 0) };
class MarketByOrder extends capnp_ts_1.Struct {
    adoptOrders(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownOrders() { return capnp_ts_1.Struct.disown(this.getOrders()); }
    getOrders() { return capnp_ts_1.Struct.getList(0, MarketByOrder._Orders, this); }
    hasOrders() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initOrders(length) { return capnp_ts_1.Struct.initList(0, MarketByOrder._Orders, length, this); }
    setOrders(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getChunk() { return capnp_ts_1.Struct.getUint32(0, this); }
    setChunk(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getNumChunks() { return capnp_ts_1.Struct.getUint32(4, this); }
    setNumChunks(value) { capnp_ts_1.Struct.setUint32(4, value, this); }
    toString() { return "MarketByOrder_" + super.toString(); }
}
exports.MarketByOrder = MarketByOrder;
MarketByOrder.Order = MarketByOrder_Order;
MarketByOrder._capnp = { displayName: "MarketByOrder", id: "8fe3db6b9f0e54b6", size: new capnp_ts_1.ObjectSize(8, 1) };
var OrderOp;
(function (OrderOp) {
    OrderOp[OrderOp["ADD"] = 0] = "ADD";
    OrderOp[OrderOp["REMOVE"] = 1] = "REMOVE";
    OrderOp[OrderOp["REPLACE"] = 2] = "REPLACE";
})(OrderOp = exports.OrderOp || (exports.OrderOp = {}));
class MarketByOrderDiff_Diff extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getExchangeOrderId() { return capnp_ts_1.Struct.getUint64(16, this); }
    setExchangeOrderId(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(24, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(24, value, this); }
    getOp() { return capnp_ts_1.Struct.getUint16(26, this); }
    setOp(value) { capnp_ts_1.Struct.setUint16(26, value, this); }
    toString() { return "MarketByOrderDiff_Diff_" + super.toString(); }
}
exports.MarketByOrderDiff_Diff = MarketByOrderDiff_Diff;
MarketByOrderDiff_Diff._capnp = { displayName: "Diff", id: "f19588f01eb3f432", size: new capnp_ts_1.ObjectSize(32, 0) };
class MarketByOrderDiff extends capnp_ts_1.Struct {
    adoptDiffs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownDiffs() { return capnp_ts_1.Struct.disown(this.getDiffs()); }
    getDiffs() { return capnp_ts_1.Struct.getList(0, MarketByOrderDiff._Diffs, this); }
    hasDiffs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiffs(length) { return capnp_ts_1.Struct.initList(0, MarketByOrderDiff._Diffs, length, this); }
    setDiffs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByOrderDiff_" + super.toString(); }
}
exports.MarketByOrderDiff = MarketByOrderDiff;
MarketByOrderDiff.Diff = MarketByOrderDiff_Diff;
MarketByOrderDiff._capnp = { displayName: "MarketByOrderDiff", id: "f414916762f10afb", size: new capnp_ts_1.ObjectSize(0, 1) };
class Trades_Trade extends capnp_ts_1.Struct {
    getTradeId() { return capnp_ts_1.Struct.getUint64(0, this); }
    setTradeId(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getPrice() { return capnp_ts_1.Struct.getUint64(8, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getAggressorSide() { return capnp_ts_1.Struct.getUint16(16, this); }
    setAggressorSide(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    getExchangeOrderId() { return capnp_ts_1.Struct.getUint64(24, this); }
    setExchangeOrderId(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    getFillQuantity() { return capnp_ts_1.Struct.getUint64(32, this); }
    setFillQuantity(value) { capnp_ts_1.Struct.setUint64(32, value, this); }
    getTransactTime() { return capnp_ts_1.Struct.getUint64(40, this); }
    setTransactTime(value) { capnp_ts_1.Struct.setUint64(40, value, this); }
    toString() { return "Trades_Trade_" + super.toString(); }
}
exports.Trades_Trade = Trades_Trade;
Trades_Trade._capnp = { displayName: "Trade", id: "8b8fa4d8ff2495d2", size: new capnp_ts_1.ObjectSize(48, 0) };
class Trades extends capnp_ts_1.Struct {
    adoptTrades(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTrades() { return capnp_ts_1.Struct.disown(this.getTrades()); }
    getTrades() { return capnp_ts_1.Struct.getList(0, Trades._Trades, this); }
    hasTrades() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTrades(length) { return capnp_ts_1.Struct.initList(0, Trades._Trades, length, this); }
    setTrades(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Trades_" + super.toString(); }
}
exports.Trades = Trades;
Trades.Trade = Trades_Trade;
Trades._capnp = { displayName: "Trades", id: "de8a15326c943241", size: new capnp_ts_1.ObjectSize(0, 1) };
class Summary extends capnp_ts_1.Struct {
    getLow() { return capnp_ts_1.Struct.getUint64(0, this); }
    setLow(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getHigh() { return capnp_ts_1.Struct.getUint64(8, this); }
    setHigh(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getBaseVolumeLo() { return capnp_ts_1.Struct.getUint64(16, this); }
    setBaseVolumeLo(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getBaseVolumeHi() { return capnp_ts_1.Struct.getUint64(24, this); }
    setBaseVolumeHi(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    getQuoteVolumeLo() { return capnp_ts_1.Struct.getUint64(32, this); }
    setQuoteVolumeLo(value) { capnp_ts_1.Struct.setUint64(32, value, this); }
    getQuoteVolumeHi() { return capnp_ts_1.Struct.getUint64(40, this); }
    setQuoteVolumeHi(value) { capnp_ts_1.Struct.setUint64(40, value, this); }
    toString() { return "Summary_" + super.toString(); }
}
exports.Summary = Summary;
Summary._capnp = { displayName: "Summary", id: "9bbd8420ea3e5219", size: new capnp_ts_1.ObjectSize(48, 0) };
var KlineInterval;
(function (KlineInterval) {
    KlineInterval[KlineInterval["S1"] = 0] = "S1";
    KlineInterval[KlineInterval["M1"] = 1] = "M1";
    KlineInterval[KlineInterval["M15"] = 2] = "M15";
    KlineInterval[KlineInterval["H1"] = 3] = "H1";
    KlineInterval[KlineInterval["H4"] = 4] = "H4";
    KlineInterval[KlineInterval["D1"] = 5] = "D1";
})(KlineInterval = exports.KlineInterval || (exports.KlineInterval = {}));
class Kline extends capnp_ts_1.Struct {
    getInterval() { return capnp_ts_1.Struct.getUint16(0, this); }
    setInterval(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    getStartTime() { return capnp_ts_1.Struct.getUint64(8, this); }
    setStartTime(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getOpen() { return capnp_ts_1.Struct.getUint64(16, this); }
    setOpen(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getClose() { return capnp_ts_1.Struct.getUint64(24, this); }
    setClose(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    getHigh() { return capnp_ts_1.Struct.getUint64(32, this); }
    setHigh(value) { capnp_ts_1.Struct.setUint64(32, value, this); }
    getLow() { return capnp_ts_1.Struct.getUint64(40, this); }
    setLow(value) { capnp_ts_1.Struct.setUint64(40, value, this); }
    getVolumeLo() { return capnp_ts_1.Struct.getUint64(48, this); }
    setVolumeLo(value) { capnp_ts_1.Struct.setUint64(48, value, this); }
    getVolumeHi() { return capnp_ts_1.Struct.getUint64(56, this); }
    setVolumeHi(value) { capnp_ts_1.Struct.setUint64(56, value, this); }
    toString() { return "Kline_" + super.toString(); }
}
exports.Kline = Kline;
Kline._capnp = { displayName: "Kline", id: "fb3b84ec44cdaa96", size: new capnp_ts_1.ObjectSize(64, 0) };
class Heartbeat extends capnp_ts_1.Struct {
    getRequestId() { return capnp_ts_1.Struct.getUint64(0, this); }
    setRequestId(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getTimestamp() { return capnp_ts_1.Struct.getUint64(8, this); }
    setTimestamp(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "Heartbeat_" + super.toString(); }
}
exports.Heartbeat = Heartbeat;
Heartbeat._capnp = { displayName: "Heartbeat", id: "b60cabec98a6709b", size: new capnp_ts_1.ObjectSize(16, 0) };
var MdMessage_Which;
(function (MdMessage_Which) {
    MdMessage_Which[MdMessage_Which["HEARTBEAT"] = 0] = "HEARTBEAT";
    MdMessage_Which[MdMessage_Which["SUMMARY"] = 1] = "SUMMARY";
    MdMessage_Which[MdMessage_Which["TRADES"] = 2] = "TRADES";
    MdMessage_Which[MdMessage_Which["MBO_SNAPSHOT"] = 3] = "MBO_SNAPSHOT";
    MdMessage_Which[MdMessage_Which["MBO_DIFF"] = 4] = "MBO_DIFF";
    MdMessage_Which[MdMessage_Which["MBP_SNAPSHOT"] = 5] = "MBP_SNAPSHOT";
    MdMessage_Which[MdMessage_Which["MBP_DIFF"] = 6] = "MBP_DIFF";
    MdMessage_Which[MdMessage_Which["KLINE"] = 7] = "KLINE";
})(MdMessage_Which = exports.MdMessage_Which || (exports.MdMessage_Which = {}));
class MdMessage extends capnp_ts_1.Struct {
    adoptHeartbeat(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownHeartbeat() { return capnp_ts_1.Struct.disown(this.getHeartbeat()); }
    getHeartbeat() {
        capnp_ts_1.Struct.testWhich("heartbeat", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, Heartbeat, this);
    }
    hasHeartbeat() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initHeartbeat() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, Heartbeat, this);
    }
    isHeartbeat() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setHeartbeat(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptSummary(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownSummary() { return capnp_ts_1.Struct.disown(this.getSummary()); }
    getSummary() {
        capnp_ts_1.Struct.testWhich("summary", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, Summary, this);
    }
    hasSummary() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSummary() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, Summary, this);
    }
    isSummary() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setSummary(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptTrades(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownTrades() { return capnp_ts_1.Struct.disown(this.getTrades()); }
    getTrades() {
        capnp_ts_1.Struct.testWhich("trades", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getStruct(0, Trades, this);
    }
    hasTrades() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTrades() {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        return capnp_ts_1.Struct.initStructAt(0, Trades, this);
    }
    isTrades() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setTrades(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptMboSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMboSnapshot() { return capnp_ts_1.Struct.disown(this.getMboSnapshot()); }
    getMboSnapshot() {
        capnp_ts_1.Struct.testWhich("mboSnapshot", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByOrder, this);
    }
    hasMboSnapshot() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMboSnapshot() {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByOrder, this);
    }
    isMboSnapshot() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setMboSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptMboDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMboDiff() { return capnp_ts_1.Struct.disown(this.getMboDiff()); }
    getMboDiff() {
        capnp_ts_1.Struct.testWhich("mboDiff", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByOrderDiff, this);
    }
    hasMboDiff() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMboDiff() {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByOrderDiff, this);
    }
    isMboDiff() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setMboDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptMbpSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMbpSnapshot() { return capnp_ts_1.Struct.disown(this.getMbpSnapshot()); }
    getMbpSnapshot() {
        capnp_ts_1.Struct.testWhich("mbpSnapshot", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByPrice, this);
    }
    hasMbpSnapshot() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMbpSnapshot() {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByPrice, this);
    }
    isMbpSnapshot() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setMbpSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptMbpDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMbpDiff() { return capnp_ts_1.Struct.disown(this.getMbpDiff()); }
    getMbpDiff() {
        capnp_ts_1.Struct.testWhich("mbpDiff", capnp_ts_1.Struct.getUint16(0, this), 6, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByPriceDiff, this);
    }
    hasMbpDiff() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMbpDiff() {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByPriceDiff, this);
    }
    isMbpDiff() { return capnp_ts_1.Struct.getUint16(0, this) === 6; }
    setMbpDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptKline(value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownKline() { return capnp_ts_1.Struct.disown(this.getKline()); }
    getKline() {
        capnp_ts_1.Struct.testWhich("kline", capnp_ts_1.Struct.getUint16(0, this), 7, this);
        return capnp_ts_1.Struct.getStruct(0, Kline, this);
    }
    hasKline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKline() {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        return capnp_ts_1.Struct.initStructAt(0, Kline, this);
    }
    isKline() { return capnp_ts_1.Struct.getUint16(0, this) === 7; }
    setKline(value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "MdMessage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.MdMessage = MdMessage;
MdMessage.HEARTBEAT = MdMessage_Which.HEARTBEAT;
MdMessage.SUMMARY = MdMessage_Which.SUMMARY;
MdMessage.TRADES = MdMessage_Which.TRADES;
MdMessage.MBO_SNAPSHOT = MdMessage_Which.MBO_SNAPSHOT;
MdMessage.MBO_DIFF = MdMessage_Which.MBO_DIFF;
MdMessage.MBP_SNAPSHOT = MdMessage_Which.MBP_SNAPSHOT;
MdMessage.MBP_DIFF = MdMessage_Which.MBP_DIFF;
MdMessage.KLINE = MdMessage_Which.KLINE;
MdMessage._capnp = { displayName: "MdMessage", id: "b94cc9b973f67840", size: new capnp_ts_1.ObjectSize(8, 1) };
class Config extends capnp_ts_1.Struct {
    getMbp() { return capnp_ts_1.Struct.getBit(0, this); }
    setMbp(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getMbo() { return capnp_ts_1.Struct.getBit(1, this); }
    setMbo(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getTrades() { return capnp_ts_1.Struct.getBit(2, this); }
    setTrades(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    getSummary() { return capnp_ts_1.Struct.getBit(3, this); }
    setSummary(value) { capnp_ts_1.Struct.setBit(3, value, this); }
    adoptKlines(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKlines() { return capnp_ts_1.Struct.disown(this.getKlines()); }
    getKlines() { return capnp_ts_1.Struct.getList(0, capnp.Uint16List, this); }
    hasKlines() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKlines(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint16List, length, this); }
    setKlines(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Config_" + super.toString(); }
}
exports.Config = Config;
Config._capnp = { displayName: "Config", id: "e35f59573ac73808", size: new capnp_ts_1.ObjectSize(8, 1) };
var ClientMessage_Which;
(function (ClientMessage_Which) {
    ClientMessage_Which[ClientMessage_Which["HEARTBEAT"] = 0] = "HEARTBEAT";
    ClientMessage_Which[ClientMessage_Which["CONFIG"] = 1] = "CONFIG";
})(ClientMessage_Which = exports.ClientMessage_Which || (exports.ClientMessage_Which = {}));
class ClientMessage extends capnp_ts_1.Struct {
    adoptHeartbeat(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownHeartbeat() { return capnp_ts_1.Struct.disown(this.getHeartbeat()); }
    getHeartbeat() {
        capnp_ts_1.Struct.testWhich("heartbeat", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, Heartbeat, this);
    }
    hasHeartbeat() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initHeartbeat() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, Heartbeat, this);
    }
    isHeartbeat() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setHeartbeat(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptConfig(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownConfig() { return capnp_ts_1.Struct.disown(this.getConfig()); }
    getConfig() {
        capnp_ts_1.Struct.testWhich("config", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, Config, this);
    }
    hasConfig() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initConfig() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, Config, this);
    }
    isConfig() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setConfig(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "ClientMessage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.ClientMessage = ClientMessage;
ClientMessage.HEARTBEAT = ClientMessage_Which.HEARTBEAT;
ClientMessage.CONFIG = ClientMessage_Which.CONFIG;
ClientMessage._capnp = { displayName: "ClientMessage", id: "adae65a9fb0eaff9", size: new capnp_ts_1.ObjectSize(8, 1) };
MarketByPrice._Levels = capnp.CompositeList(MarketByPrice_Level);
MarketByPriceDiff._Diffs = capnp.CompositeList(MarketByPriceDiff_Diff);
MarketByOrder._Orders = capnp.CompositeList(MarketByOrder_Order);
MarketByOrderDiff._Diffs = capnp.CompositeList(MarketByOrderDiff_Diff);
Trades._Trades = capnp.CompositeList(Trades_Trade);
