"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Heartbeat = exports.MarketByOrderMessage = exports.MarketByOrderMessage_Which = exports.MarketByOrderDiff = exports.MarketByOrderDiff_Diff = exports.OrderOp = exports.MarketByOrder = exports.MarketByOrder_Order = exports.MarketByPriceMessage = exports.MarketByPriceMessage_Which = exports.MarketByPriceDiff = exports.MarketByPriceDiff_Diff = exports.DiffOp = exports.MarketByPrice = exports.MarketByPrice_Level = exports.Side = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = BigInt("0x9c4a7243ef808f4c");
var Side;
(function (Side) {
    Side[Side["BID"] = 0] = "BID";
    Side[Side["ASK"] = 1] = "ASK";
})(Side = exports.Side || (exports.Side = {}));
class MarketByPrice_Level extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(16, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    toString() { return "MarketByPrice_Level_" + super.toString(); }
}
exports.MarketByPrice_Level = MarketByPrice_Level;
MarketByPrice_Level._capnp = { displayName: "Level", id: "987a7e078dee1837", size: new capnp_ts_1.ObjectSize(24, 0) };
class MarketByPrice extends capnp_ts_1.Struct {
    adoptLevels(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownLevels() { return capnp_ts_1.Struct.disown(this.getLevels()); }
    getLevels() { return capnp_ts_1.Struct.getList(0, MarketByPrice._Levels, this); }
    hasLevels() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initLevels(length) { return capnp_ts_1.Struct.initList(0, MarketByPrice._Levels, length, this); }
    setLevels(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByPrice_" + super.toString(); }
}
exports.MarketByPrice = MarketByPrice;
MarketByPrice.Level = MarketByPrice_Level;
MarketByPrice._capnp = { displayName: "MarketByPrice", id: "f3322fc4d3725060", size: new capnp_ts_1.ObjectSize(0, 1) };
var DiffOp;
(function (DiffOp) {
    DiffOp[DiffOp["ADD"] = 0] = "ADD";
    DiffOp[DiffOp["REMOVE"] = 1] = "REMOVE";
    DiffOp[DiffOp["REPLACE"] = 2] = "REPLACE";
})(DiffOp = exports.DiffOp || (exports.DiffOp = {}));
class MarketByPriceDiff_Diff extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getOp() { return capnp_ts_1.Struct.getUint16(16, this); }
    setOp(value) { capnp_ts_1.Struct.setUint16(16, value, this); }
    toString() { return "MarketByPriceDiff_Diff_" + super.toString(); }
}
exports.MarketByPriceDiff_Diff = MarketByPriceDiff_Diff;
MarketByPriceDiff_Diff._capnp = { displayName: "Diff", id: "f248c3f0ab609a5b", size: new capnp_ts_1.ObjectSize(24, 0) };
class MarketByPriceDiff extends capnp_ts_1.Struct {
    adoptDiffs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownDiffs() { return capnp_ts_1.Struct.disown(this.getDiffs()); }
    getDiffs() { return capnp_ts_1.Struct.getList(0, MarketByPriceDiff._Diffs, this); }
    hasDiffs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiffs(length) { return capnp_ts_1.Struct.initList(0, MarketByPriceDiff._Diffs, length, this); }
    setDiffs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByPriceDiff_" + super.toString(); }
}
exports.MarketByPriceDiff = MarketByPriceDiff;
MarketByPriceDiff.Diff = MarketByPriceDiff_Diff;
MarketByPriceDiff._capnp = { displayName: "MarketByPriceDiff", id: "d0332521c2c8b8c0", size: new capnp_ts_1.ObjectSize(0, 1) };
var MarketByPriceMessage_Which;
(function (MarketByPriceMessage_Which) {
    MarketByPriceMessage_Which[MarketByPriceMessage_Which["SNAPSHOT"] = 0] = "SNAPSHOT";
    MarketByPriceMessage_Which[MarketByPriceMessage_Which["DIFF"] = 1] = "DIFF";
})(MarketByPriceMessage_Which = exports.MarketByPriceMessage_Which || (exports.MarketByPriceMessage_Which = {}));
class MarketByPriceMessage extends capnp_ts_1.Struct {
    adoptSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownSnapshot() { return capnp_ts_1.Struct.disown(this.getSnapshot()); }
    getSnapshot() {
        capnp_ts_1.Struct.testWhich("snapshot", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByPrice, this);
    }
    hasSnapshot() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSnapshot() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByPrice, this);
    }
    isSnapshot() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownDiff() { return capnp_ts_1.Struct.disown(this.getDiff()); }
    getDiff() {
        capnp_ts_1.Struct.testWhich("diff", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByPriceDiff, this);
    }
    hasDiff() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiff() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByPriceDiff, this);
    }
    isDiff() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "MarketByPriceMessage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.MarketByPriceMessage = MarketByPriceMessage;
MarketByPriceMessage.SNAPSHOT = MarketByPriceMessage_Which.SNAPSHOT;
MarketByPriceMessage.DIFF = MarketByPriceMessage_Which.DIFF;
MarketByPriceMessage._capnp = { displayName: "MarketByPriceMessage", id: "8d0167eb8221ff1d", size: new capnp_ts_1.ObjectSize(8, 1) };
class MarketByOrder_Order extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getExchangeOrderId() { return capnp_ts_1.Struct.getUint64(16, this); }
    setExchangeOrderId(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(24, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(24, value, this); }
    toString() { return "MarketByOrder_Order_" + super.toString(); }
}
exports.MarketByOrder_Order = MarketByOrder_Order;
MarketByOrder_Order._capnp = { displayName: "Order", id: "f3945c08e6ddb772", size: new capnp_ts_1.ObjectSize(32, 0) };
class MarketByOrder extends capnp_ts_1.Struct {
    adoptOrders(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownOrders() { return capnp_ts_1.Struct.disown(this.getOrders()); }
    getOrders() { return capnp_ts_1.Struct.getList(0, MarketByOrder._Orders, this); }
    hasOrders() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initOrders(length) { return capnp_ts_1.Struct.initList(0, MarketByOrder._Orders, length, this); }
    setOrders(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByOrder_" + super.toString(); }
}
exports.MarketByOrder = MarketByOrder;
MarketByOrder.Order = MarketByOrder_Order;
MarketByOrder._capnp = { displayName: "MarketByOrder", id: "8fe3db6b9f0e54b6", size: new capnp_ts_1.ObjectSize(0, 1) };
var OrderOp;
(function (OrderOp) {
    OrderOp[OrderOp["ADD"] = 0] = "ADD";
    OrderOp[OrderOp["REMOVE"] = 1] = "REMOVE";
    OrderOp[OrderOp["REPLACE"] = 2] = "REPLACE";
})(OrderOp = exports.OrderOp || (exports.OrderOp = {}));
class MarketByOrderDiff_Diff extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getUint64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQuantity() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQuantity(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getExchangeOrderId() { return capnp_ts_1.Struct.getUint64(16, this); }
    setExchangeOrderId(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getSide() { return capnp_ts_1.Struct.getUint16(24, this); }
    setSide(value) { capnp_ts_1.Struct.setUint16(24, value, this); }
    getOp() { return capnp_ts_1.Struct.getUint16(26, this); }
    setOp(value) { capnp_ts_1.Struct.setUint16(26, value, this); }
    toString() { return "MarketByOrderDiff_Diff_" + super.toString(); }
}
exports.MarketByOrderDiff_Diff = MarketByOrderDiff_Diff;
MarketByOrderDiff_Diff._capnp = { displayName: "Diff", id: "f19588f01eb3f432", size: new capnp_ts_1.ObjectSize(32, 0) };
class MarketByOrderDiff extends capnp_ts_1.Struct {
    adoptDiffs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownDiffs() { return capnp_ts_1.Struct.disown(this.getDiffs()); }
    getDiffs() { return capnp_ts_1.Struct.getList(0, MarketByOrderDiff._Diffs, this); }
    hasDiffs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiffs(length) { return capnp_ts_1.Struct.initList(0, MarketByOrderDiff._Diffs, length, this); }
    setDiffs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MarketByOrderDiff_" + super.toString(); }
}
exports.MarketByOrderDiff = MarketByOrderDiff;
MarketByOrderDiff.Diff = MarketByOrderDiff_Diff;
MarketByOrderDiff._capnp = { displayName: "MarketByOrderDiff", id: "f414916762f10afb", size: new capnp_ts_1.ObjectSize(0, 1) };
var MarketByOrderMessage_Which;
(function (MarketByOrderMessage_Which) {
    MarketByOrderMessage_Which[MarketByOrderMessage_Which["SNAPSHOT"] = 0] = "SNAPSHOT";
    MarketByOrderMessage_Which[MarketByOrderMessage_Which["DIFF"] = 1] = "DIFF";
})(MarketByOrderMessage_Which = exports.MarketByOrderMessage_Which || (exports.MarketByOrderMessage_Which = {}));
class MarketByOrderMessage extends capnp_ts_1.Struct {
    adoptSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownSnapshot() { return capnp_ts_1.Struct.disown(this.getSnapshot()); }
    getSnapshot() {
        capnp_ts_1.Struct.testWhich("snapshot", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByOrder, this);
    }
    hasSnapshot() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSnapshot() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByOrder, this);
    }
    isSnapshot() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setSnapshot(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownDiff() { return capnp_ts_1.Struct.disown(this.getDiff()); }
    getDiff() {
        capnp_ts_1.Struct.testWhich("diff", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, MarketByOrderDiff, this);
    }
    hasDiff() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDiff() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, MarketByOrderDiff, this);
    }
    isDiff() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setDiff(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "MarketByOrderMessage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.MarketByOrderMessage = MarketByOrderMessage;
MarketByOrderMessage.SNAPSHOT = MarketByOrderMessage_Which.SNAPSHOT;
MarketByOrderMessage.DIFF = MarketByOrderMessage_Which.DIFF;
MarketByOrderMessage._capnp = { displayName: "MarketByOrderMessage", id: "e8b30dfd93fdf623", size: new capnp_ts_1.ObjectSize(8, 1) };
class Heartbeat extends capnp_ts_1.Struct {
    toString() { return "Heartbeat_" + super.toString(); }
}
exports.Heartbeat = Heartbeat;
Heartbeat._capnp = { displayName: "Heartbeat", id: "b60cabec98a6709b", size: new capnp_ts_1.ObjectSize(0, 0) };
MarketByPrice._Levels = capnp.CompositeList(MarketByPrice_Level);
MarketByPriceDiff._Diffs = capnp.CompositeList(MarketByPriceDiff_Diff);
MarketByOrder._Orders = capnp.CompositeList(MarketByOrder_Order);
MarketByOrderDiff._Diffs = capnp.CompositeList(MarketByOrderDiff_Diff);
